# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

apiVersion: v1
kind: Namespace
metadata:
  name: sriov-fec-operator-resources
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sriov-device-plugin
  namespace: sriov-fec-operator-resources
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sriov-plugin
  namespace: sriov-fec-operator-resources
rules:
  - apiGroups:
      - security.openshift.io
    resourceNames:
      - privileged
    resources:
      - securitycontextconstraints
    verbs:
      - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sriov-device-plugin
  namespace: sriov-fec-operator-resources
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sriov-plugin
subjects:
  - kind: ServiceAccount
    name: sriov-device-plugin
    namespace: sriov-fec-operator-resources
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sriovdp-config
  namespace: sriov-fec-operator-resources
data:
  config.json: |
    {
        "resourceList": [
            {
                "resourceName": "intel_fec_lte",
                "deviceType": "accelerator",
                "selectors": {
                    "vendors": ["1172"],
                    "devices": ["5050"],
                    "drivers": ["pci-pf-stub", "vfio-pci"]
                }
            },
            {
                "resourceName": "intel_fec_5g",
                "deviceType": "accelerator",
                "selectors": {
                    "vendors": ["8086"],
                    "devices": ["0d90"],
                    "drivers": ["pci-pf-stub", "vfio-pci"]
                }
            }
        ]
    }
---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: sriov-device-plugin
  namespace: sriov-fec-operator-resources
  labels:
    app: sriov-device-plugin-daemonset
spec:
  minReadySeconds: 10
  selector:
    matchLabels:
      app: sriov-device-plugin-daemonset
  template:
    metadata:
      labels:
        app: sriov-device-plugin-daemonset
    spec:
      hostNetwork: true
      nodeSelector:
        feature.node.kubernetes.io/pci-8086.present: "true"
      serviceAccountName: sriov-device-plugin
      containers:
      - name: sriov-device-plugin
        image: nfvpe/sriov-device-plugin:v3.2
        args:
        - --log-level=10
        securityContext:
          privileged: true
        volumeMounts:
        - name: devicesock
          mountPath: /var/lib/kubelet/
          readOnly: false
        - name: config-volume
          mountPath: /etc/pcidp/
          readOnly: true
      volumes:
        - name: devicesock
          hostPath:
            path: /var/lib/kubelet/
        - name: net
          hostPath:
            path: /sys/class/net
        - name: config-volume
          configMap:
            name: sriovdp-config
            items:
            - key: config.json
              path: config.json
