# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020-2021 Intel Corporation

apiVersion: v1
kind: ServiceAccount
metadata:
  name: sriov-fec-daemon
  namespace: n3000-operators-resources

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sriov-fec-daemon
  namespace: n3000-operators-resources
rules:
- apiGroups:
  - sriovfec.intel.com
  resources:
  - '*'
  - sriov-fecnodes
  verbs:
  - '*'
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - use
  resourceNames:
  - privileged
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - '*'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sriov-fec-daemon
  namespace: n3000-operators-resources
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sriov-fec-daemon
  namespace: n3000-operators-resources
subjects:
- kind: ServiceAccount
  name: sriov-fec-daemon
  namespace: n3000-operators-resources
userNames:
- system:serviceaccount:n3000-operators-resources:sriov-fec-daemon

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sriov-fec-daemon
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch", "patch", "update"]
- apiGroups: ["apps"]
  resources: ["daemonsets"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["pods/eviction"]
  verbs: ["create"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sriov-fec-daemon
subjects:
- kind: ServiceAccount
  name: sriov-fec-daemon
  namespace: n3000-operators-resources
roleRef:
  kind: ClusterRole
  name: sriov-fec-daemon
  apiGroup: rbac.authorization.k8s.io
  namespace: n3000-operators-resources

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: sriov-fec-daemonset
  name: sriov-fec-daemonset
  namespace: n3000-operators-resources
  annotations:
    openshift.io/scc: sriov-fec-daemon
spec:
  selector:
    matchLabels:
      app: sriov-fec-daemonset
  template:
    metadata:
      # Mark this pod as a critical add-on; when enabled, the critical add-on scheduler
      # reserves resources for critical add-on pods so that they can be rescheduled after
      # a failure.  This annotation works in tandem with the toleration below.
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
      labels:
        app: sriov-fec-daemonset
    spec:
      nodeSelector:
        fpga.intel.com/intel-accelerator-present: ""
      tolerations:
      - key: intel.com/sriovfec
        operator: Exists
        effect: NoSchedule
      serviceAccount: sriov-fec-daemon
      serviceAccountName: sriov-fec-daemon
      hostPID: true
      hostNetwork: true
      containers:
      - name: sriov-fec-daemon
        image: "{{ .SRIOV_FEC_DAEMON_IMAGE }}"
        imagePullPolicy: IfNotPresent
        args:
        - --zap-devel
        - --zap-log-level=4
        volumeMounts:
        - name: host
          mountPath: /host
        - name: sysbuspci
          mountPath: /sys/bus/pci
        - name: workdir-volume
          mountPath: /sriov_artifacts
        - name: tmp-volume
          mountPath: /tmp
        - name: run-volume
          mountPath: /run
        - name: config-volume
          mountPath: /sriov_config/config
          readOnly: true
        env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: NODENAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: DRAIN_TIMEOUT_SECONDS
            value: "90"
          - name: LEASE_DURATION_SECONDS
            value: "600"
        securityContext:
          readOnlyRootFilesystem: true
          privileged: true
      volumes:
      - name: host
        hostPath:
          path: /
      - name: sysbuspci
        hostPath:
          path: /sys/bus/pci
      - name: workdir-volume
        emptyDir: {}
      - name: tmp-volume
        emptyDir: {}
      - name: run-volume
        emptyDir: {}
      - name: config-volume
        configMap:
          name: supported-accelerators
          items:
          - key: accelerators.json
            path: accelerators.json
