# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

apiVersion: v1
kind: Namespace
metadata:
  name: n3000-operators-resources
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: n3000-discovery
  namespace: n3000-operators-resources
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: n3000-discovery
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: n3000-discovery
  namespace: n3000-operators-resources
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: n3000-discovery
  namespace: n3000-operators-resources
subjects:
- kind: ServiceAccount
  name: n3000-discovery
  namespace: n3000-operators-resources
userNames:
- system:serviceaccount:n3000-operators-resources:n3000-discovery

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: n3000-labeler-config
  namespace: n3000-operators-resources
data:
  accelerators.json: |
    {
      "VendorID": "8086",
      "Class": "12",
      "SubClass": "00",
      "Devices": {
        "0d8f": "FPGA_5GNR",
        "5052": "FPGA_LTE",
        "0b32": ""
      },
      "NodeLabel": "fpga.intel.com/intel-accelerator-present"
    }

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: n3000-discovery
  name: n3000-discovery
  namespace: n3000-operators-resources
spec:
  minReadySeconds: 10
  selector:
    matchLabels:
      app: n3000-discovery
  template:
    metadata:
      labels:
        app: n3000-discovery
      name: n3000-discovery
    spec:
      serviceAccount: n3000-discovery
      serviceAccountName: n3000-discovery
      containers:
      - image: "{{ .N3000_LABELER_IMAGE }}"
        name: n3000-discovery
        securityContext:
          readOnlyRootFilesystem: true
        volumeMounts:
        - name: config-volume
          mountPath: "/labeler-workspace/config"
          readOnly: true
        env:
          - name: NODENAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
      volumes:
        - name: config-volume
          configMap:
            name: n3000-labeler-config
            items:
            - key: accelerators.json
              path: accelerators.json
