# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

apiVersion: sriovfec.intel.com/v1
kind: SriovFecClusterConfig
metadata:
  name: config
spec:
  # if true, then the 1st node object will be used to configure all nodes, nodeName will be ignored
  # 1st card object will be taken, pci_addr will be ignored
  oneNodeConfigForAll: true
  nodes:
    - nodeName: ""
      # if true, then 1st card object will be used to configure all cards on the node
      # pci_addr will be ignored
      oneCardConfigForAll: true
      cards:
        - pciAddress: ""
          vendorID: "8086"
          pfDeviceID: "0d8f"
          pfDriver: "pci-pf-stub"
          vfDeviceID: "0d90"
          vfDriver: "vfio-pci"
          vfAmount: 2
          queuesConfiguration:
            # Network Type: either "FPGA_5GNR" or "FPGA_LTE"
            networkType: "FPGA_5GNR"
            # Programming mode: 0 = VF Programming, 1 = PF Programming
            pfMode: true
            flrTimeout: 610
            downlink:
              bandwidth: 3
              loadBalance: 128
              queues:
                vf0: 16
                vf1: 16
                vf2: 0
                vf3: 0
                vf4: 0
                vf5: 0
                vf6: 0
                vf7: 0
            uplink:
              bandwidth: 3
              loadBalance: 128
              queues:
                vf0: 16
                vf1: 16
                vf2: 0
                vf3: 0
                vf4: 0
                vf5: 0
                vf6: 0
                vf7: 0
