
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - sriovfec.intel.com
  resources:
  - sriovfecclusterconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sriovfec.intel.com
  resources:
  - sriovfecclusterconfigs/status
  verbs:
  - get
  - patch
  - update
