# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation


---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - namespaces
  - serviceaccounts
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - list
- apiGroups:
  - apps
  resources:
  - daemonsets
  verbs:
  - '*'
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - clusterroles
  - rolebindings
  - roles
  verbs:
  - '*'
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - '*'
- apiGroups:
  - sriovfec.intel.com
  resources:
  - sriovfecclusterconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sriovfec.intel.com
  resources:
  - sriovfecclusterconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - sriovfec.intel.com
  resources:
  - sriovfecnodeconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sriovfec.intel.com
  resources:
  - sriovfecnodeconfigs/status
  verbs:
  - get
  - patch
  - update
