# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: n3000-operator
  newName: n3000-operator
  newTag: v1.0.0
