# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020-2021 Intel Corporation

apiVersion: v1
kind: ConfigMap
metadata:
  name: daemon-config
  namespace: {{ .SRIOV_FEC_NAMESPACE }}
immutable: false
data:
  serviceAccount: |
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: sriov-fec-daemon
      namespace: {{ .SRIOV_FEC_NAMESPACE }}
  role: |
    apiVersion: rbac.authorization.k8s.io/v1
    kind: Role
    metadata:
      name: sriov-fec-daemon
      namespace: {{ .SRIOV_FEC_NAMESPACE }}
    rules:
    - apiGroups:
      - sriovfec.intel.com
      resources:
      - '*'
      - sriov-fecnodes
      verbs:
      - '*'
    - apiGroups:
      - security.openshift.io
      resources:
      - securitycontextconstraints
      verbs:
      - use
      resourceNames:
      - privileged
    - apiGroups:
      - coordination.k8s.io
      resources:
      - leases
      verbs:
      - '*'
  roleBinding: |
    apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: sriov-fec-daemon
      namespace: {{ .SRIOV_FEC_NAMESPACE }}
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: Role
      name: sriov-fec-daemon
      {{ if eq (.SRIOV_FEC_GENERIC_K8S|ToLower) `false` }}
      namespace: {{ .SRIOV_FEC_NAMESPACE }}
      {{ end }}
    subjects:
    - kind: ServiceAccount
      name: sriov-fec-daemon
      namespace: {{ .SRIOV_FEC_NAMESPACE }}
      {{ if eq (.SRIOV_FEC_GENERIC_K8S|ToLower) `false` }}
    userNames:
    - system:serviceaccount:{{ .SRIOV_FEC_NAMESPACE }}:sriov-fec-daemon
      {{ end }}
  clusterRole: |
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      name: sriov-fec-daemon
    rules:
    - apiGroups: [""]
      resources: ["pods"]
      verbs: ["*"]
    - apiGroups: [""]
      resources: ["nodes"]
      verbs: ["get", "list", "watch", "patch", "update"]
    - apiGroups: ["apps"]
      resources: ["daemonsets"]
      verbs: ["get"]
    - apiGroups: [""]
      resources: ["pods/eviction"]
      verbs: ["create"]
  clusterRoleBinding: |
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: sriov-fec-daemon
    subjects:
    - kind: ServiceAccount
      name: sriov-fec-daemon
      namespace: {{ .SRIOV_FEC_NAMESPACE }}
    roleRef:
      kind: ClusterRole
      name: sriov-fec-daemon
      apiGroup: rbac.authorization.k8s.io
      namespace: {{ .SRIOV_FEC_NAMESPACE }}
  secret: |
    apiVersion: v1
    kind: Secret
    metadata:
      name: vfio-token
      namespace: {{ .SRIOV_FEC_NAMESPACE }}
    type: Opaque
    stringData:
      VFIO_TOKEN: 02bddbbf-bbb0-4d79-886b-91bad3fbb510
    immutable: true
  daemonSet: |
    apiVersion: apps/v1
    kind: DaemonSet
    metadata:
      labels:
        app: sriov-fec-daemonset
      name: sriov-fec-daemonset
      namespace: {{ .SRIOV_FEC_NAMESPACE }}
      annotations:
        openshift.io/scc: sriov-fec-daemon
    spec:
      selector:
        matchLabels:
          app: sriov-fec-daemonset
      template:
        metadata:
          # Mark this pod as a critical add-on; when enabled, the critical add-on scheduler
          # reserves resources for critical add-on pods so that they can be rescheduled after
          # a failure.  This annotation works in tandem with the toleration below.
          annotations:
            scheduler.alpha.kubernetes.io/critical-pod: ""
          labels:
            app: sriov-fec-daemonset
        spec:
          nodeSelector:
            fpga.intel.com/intel-accelerator-present: ""
          tolerations:
          - key: intel.com/sriovfec
            operator: Exists
            effect: NoSchedule
          serviceAccount: sriov-fec-daemon
          serviceAccountName: sriov-fec-daemon
          hostPID: true
          hostNetwork: true
          dnsPolicy: ClusterFirstWithHostNet
          containers:
          - name: sriov-fec-daemon
            image: {{ .SRIOV_FEC_DAEMON_IMAGE }}
            imagePullPolicy: IfNotPresent
            volumeMounts:
            - name: devvfio
              mountPath: /dev/vfio             
            - name: vfiotoken
              mountPath: /sriov_config/
              readOnly: true    
            - name: sysbuspci
              mountPath: /sys/bus/pci
            - mountPath: /sriov_artifacts
              name: workdir-volume
            - mountPath: /sriov_config/config
              name: config-volume
              readOnly: true
            - mountPath: /host/lib
              name: lib
            - mountPath: /host/lib64
              name: lib64
            - mountPath: /host/proc
              name: proc
            - mountPath: /host/usr/bin
              name: bin
            - mountPath: /host/usr/sbin
              name: sbin
            - name: logs
              mountPath: /var/log
            - name: tmp
              mountPath: /tmp    
            env:
              - name: SRIOV_FEC_NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
              - name: NODENAME
                valueFrom:
                  fieldRef:
                    fieldPath: spec.nodeName
              - name: DRAIN_TIMEOUT_SECONDS
                value: "90"
              - name: LEASE_DURATION_SECONDS
                value: "600"
            securityContext:
              readOnlyRootFilesystem: true
              privileged: true
      {{ if eq (.SRIOV_FEC_GENERIC_K8S|ToLower) `true` }}
              runAsUser: 0
              capabilities:
                add:
                  - "ALL"
      {{ end }}
          volumes:
          - hostPath:
              path: /sys/bus/pci
            name: sysbuspci
          - emptyDir: {}
            name: workdir-volume
          - configMap:
              defaultMode: 420
              items:
              - key: accelerators.json
                path: accelerators.json
              name: supported-accelerators
            name: config-volume
          - name: vfiotoken
            secret:
              secretName: vfio-token
              optional: false
              items:
               - key: VFIO_TOKEN
                 path: vfiotoken
          - hostPath:
              path: /usr/lib
              type: ""
            name: lib
          - hostPath:
              path: /usr/lib64
              type: ""
            name: lib64
          - hostPath:
              path: /usr/bin
              type: ""
            name: bin
          - hostPath:
              path: /usr/sbin
              type: ""
            name: sbin
          - hostPath:
              path: /proc
              type: ""
            name: proc
          - hostPath:
              path: /dev/vfio
              type: ""
            name: devvfio
          - name: logs
            emptyDir: {}
          - name: tmp
            emptyDir: {}    
