# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: n3000-metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
