# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

apiVersion: fpga.intel.com/v1
kind: N3000Cluster
metadata:
  name: n3000cluster-sample
spec:
  # Add fields here
  foo: bar
